FROM python
RUN pip3 install flask -i https://pypi.tuna.tsinghua.edu.cn/simple
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/sample_app.py
FROM python
RUN pip3 install flask -i https://pypi.tuna.tsinghua.edu.cn/simple
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/sample_app.py
FROM python
RUN pip3 install flask -i https://pypi.tuna.tsinghua.edu.cn/simple
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/sample_app.py
FROM python
RUN pip3 install flask -i https://pypi.tuna.tsinghua.edu.cn/simple
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/sample_app.py
